const pond_pl = {
  // labelIdle: 'Drag & Drop your files or <span class="filepond--label-action"> Browse </span>'
  labelIdle: 'Wybierz i dodaj zdjęcia... 🔍',
  // labelInvalidField: 'Field contains invalid files',
  labelInvalidField: 'Pole zawiera nieprawidłowe pliki',
  // labelFileWaitingForSize: 'Waiting for size',
  labelFileWaitingForSize: 'Oczekiwanie na rozmiar pliku',
  // labelFileSizeNotAvailable: 'Size not available',
  labelFileSizeNotAvailable: 'Rozmiar pliku niedostępny',
  // labelFileLoading: 'Loading',
  labelFileLoading: 'Wczytywanie',
  // labelFileLoadError: 'Error during load',
  labelFileLoadError: 'Wystąpił błąd',
  // labelFileProcessing: 'Uploading',
  labelFileProcessing: 'Wgrywanie',
  // labelFileProcessingComplete: 'Upload complete',
  labelFileProcessingComplete: 'Wgrywanie zakończone',
  // labelFileProcessingAborted: 'Upload cancelled',
  labelFileProcessingAborted: 'Wgrywanie przerwane',
  // labelFileProcessingError: 'Error during upload',
  labelFileProcessingError: 'Wystąpił błąd',
  // labelFileProcessingRevertError: 'Error during revert',
  labelFileProcessingRevertError: 'Wystąpił błąd',
  // labelFileRemoveError: 'Error during remove',
  labelFileRemoveError: 'Wystąpił błąd',
  // labelTapToCancel: 'tap to cancel',
  labelTapToCancel: 'kliknij aby anulować',
  // labelTapToRetry: 'tap to retry',
  labelTapToRetry: 'kliknij aby ponowić',
  // labelTapToUndo: 'tap to undo',
  labelTapToUndo: 'kliknij aby usunąć',
  // labelButtonRemoveItem: 'Remove',
  labelButtonRemoveItem: 'Usuń',
  // labelButtonAbortItemLoad: 'Abort',
  labelButtonAbortItemLoad: 'Zrezygnuj',
  // labelButtonRetryItemLoad: 'Retry',
  labelButtonRetryItemLoad: 'Ponów',
  // labelButtonAbortItemProcessing: 'Cancel',
  labelButtonAbortItemProcessing: 'Anuluj',
  // labelButtonUndoItemProcessing: 'Undo',
  labelButtonUndoItemProcessing: 'Cofnij',
  // labelButtonRetryItemProcessing: 'Retry',
  labelButtonRetryItemProcessing: 'Spróbuj',
  // labelButtonProcessItem: 'Upload',
  labelButtonProcessItem: 'Wgrywanie',
  // labelMaxFileSizeExceeded: 'File is too large',
  labelMaxFileSizeExceeded: 'Plik jest za duży',
  // labelMaxFileSize: 'Maximum file size is {filesize}',
  labelMaxFileSize: 'Maksymalna wielkość pliku: {filesize}',
  // labelMaxTotalFileSizeExceeded: 'Maximum total size exceeded',
  labelMaxTotalFileSizeExceeded: 'Przekroczony maksymalny rozmiar pliku',
  // labelMaxTotalFileSize: 'Maximum total file size is {filesize}',
  labelMaxTotalFileSize: 'Maksymalny rozmiar pliku: {filesize}',
  // labelFileTypeNotAllowed: 'File of invalid type',
  labelFileTypeNotAllowed: 'Błędny typ pliku',
  // fileValidateTypeLabelExpectedTypes: 'Expects {allButLastType} or {lastType}',
  //fileValidateTypeLabelExpectedTypes:
  // imageValidateSizeLabelFormatError: 'Image type not supported',
  imageValidateSizeLabelFormatError: 'Nieodpowiedni typ pliku',
  // imageValidateSizeLabelImageSizeTooSmall: 'Image is too small',
  imageValidateSizeLabelImageSizeTooSmall: 'Plik jest zbyt mały',
  // imageValidateSizeLabelImageSizeTooBig: 'Image is too big',
  imageValidateSizeLabelImageSizeTooBig: 'Plik jest zbyt duży',
  // imageValidateSizeLabelExpectedMinSize: 'Minimum size is {minWidth} × {minHeight}',
  imageValidateSizeLabelExpectedMinSize:
    'Minimalne wymiary: {minWidth} × {minHeight}',
  // imageValidateSizeLabelExpectedMaxSize: 'Maximum size is {maxWidth} × {maxHeight}',
  imageValidateSizeLabelExpectedMaxSize:
    'Maksymalne wymiary: {maxWidth} × {maxHeight}',
  // imageValidateSizeLabelImageResolutionTooLow: 'Resolution is too low',
  imageValidateSizeLabelImageResolutionTooLow: 'Zbyt niska rozdzielczość',
  // imageValidateSizeLabelImageResolutionTooHigh: 'Resolution is too high',
  imageValidateSizeLabelImageResolutionTooHigh: 'Zbyt wysoka rozdzielczość',
  // imageValidateSizeLabelExpectedMinResolution: 'Minimum resolution is {minResolution}',
  imageValidateSizeLabelExpectedMinResolution:
    'Minimalna rozdzielczość: {minResolution}',
  // imageValidateSizeLabelExpectedMaxResolution: 'Maximum resolution is {maxResolution}'
  imageValidateSizeLabelExpectedMaxResolution:
    'Maksymalna rozdzielczość: {maxResolution}',
}

export default pond_pl
